### ISSUE TITLE
Frequently getting SERVFAIL for some websites

### ISSUE THREAD

**Issue by chriexpe** [origamiofficial/docker-pihole-unbound#18] opened 2024-01-13 19:32 UTC
Latelly I've been getting a ton of SERVFAIL errors with some websites like bing, home assistant etc., tried a fresh version of the docker but the issue persisted, I enabled verbosing 3 and this is the Unbound logs:
```
debug: sending to target: <cloudflare.com.> 2400:cb00:2049:1::a29f:209#53

2024-01-13T19:14:43.358684652Z [1705173283] unbound[246:2] debug: cache memory msg=809710 rrset=1894059 infra=1461806 val=201264 subnet=74536

2024-01-13T19:14:43.358699022Z [1705173283] unbound[246:2] debug: iterator[module 2] operate: extstate:module_wait_reply event:module_event_noreply

2024-01-13T19:14:43.358713355Z [1705173283] unbound[246:2] info: iterator operate: query owen.ns.cloudflare.com. AAAA IN

2024-01-13T19:14:43.358727410Z [1705173283] unbound[246:2] info: processQueryTargets: owen.ns.cloudflare.com. AAAA IN

2024-01-13T19:14:43.358741539Z [1705173283] unbound[246:2] debug: request has exceeded the maximum number of sends with 33

2024-01-13T19:14:43.358755854Z [1705173283] unbound[246:2] debug: return error response SERVFAIL

2024-01-13T19:14:43.358769872Z [1705173283] unbound[246:2] debug: validator[module 1] operate: extstate:module_state_initial event:module_event_moddone

2024-01-13T19:14:43.358784168Z [1705173283] unbound[246:2] info: validator operate: query owen.ns.cloudflare.com. AAAA IN

2024-01-13T19:14:43.358798482Z [1705173283] unbound[246:2] debug: subnetcache[module 0] operate: extstate:module_state_initial event:module_event_moddone

2024-01-13T19:14:43.358812908Z [1705173283] unbound[246:2] info: subnetcache operate: query owen.ns.cloudflare.com. AAAA IN

2024-01-13T19:14:43.358827130Z [1705173283] unbound[246:2] debug: iterator[module 2] operate: extstate:module_wait_subquery event:module_event_pass

2024-01-13T19:14:43.358842185Z [1705173283] unbound[246:2] info: iterator operate: query x2.c.lencr.org. AAAA IN

2024-01-13T19:14:43.358856407Z [1705173283] unbound[246:2] info: processQueryTargets: x2.c.lencr.org. AAAA IN

2024-01-13T19:14:43.358871962Z [1705173283] unbound[246:2] debug: iterator[module 2] operate: extstate:module_wait_subquery event:module_event_pass

2024-01-13T19:14:43.358906813Z [1705173283] unbound[246:2] info: iterator operate: query x2.c.lencr.org. A IN

2024-01-13T19:14:43.358921924Z [1705173283] unbound[246:2] info: processQueryTargets: x2.c.lencr.org. A IN

2024-01-13T19:14:43.358936368Z [1705173283] unbound[246:2] debug: cache memory msg=809710 rrset=1894059 infra=1461806 val=201264 subnet=74536

2024-01-13T19:14:43.358950831Z [1705173283] unbound[246:2] debug: iterator[module 2] operate: extstate:module_wait_reply event:module_event_noreply

2024-01-13T19:14:43.358965164Z [1705173283] unbound[246:2] info: iterator operate: query owen.ns.cloudflare.com. A IN

2024-01-13T19:14:43.358979275Z [1705173283] unbound[246:2] info: processQueryTargets: owen.ns.cloudflare.com. A IN

2024-01-13T19:14:43.358993385Z [1705173283] unbound[246:2] debug: request has exceeded the maximum number of sends with 33

2024-01-13T19:14:43.359007441Z [1705173283] unbound[246:2] debug: return error response SERVFAIL

2024-01-13T19:14:43.359021459Z [1705173283] unbound[246:2] debug: validator[module 1] operate: extstate:module_state_initial event:module_event_moddone

2024-01-13T19:14:43.359035829Z [1705173283] unbound[246:2] info: validator operate: query owen.ns.cloudflare.com. A IN

2024-01-13T19:14:43.359050162Z [1705173283] unbound[246:2] debug: subnetcache[module 0] operate: extstate:module_state_initial event:module_event_moddone

2024-01-13T19:14:43.359064495Z [1705173283] unbound[246:2] info: subnetcache operate: query owen.ns.cloudflare.com. A IN

2024-01-13T19:14:43.359078717Z [1705173283] unbound[246:2] debug: iterator[module 2] operate: extstate:module_wait_subquery event:module_event_pass

2024-01-13T19:14:43.359093013Z [1705173283] unbound[246:2] info: iterator operate: query x2.c.lencr.org. AAAA IN

2024-01-13T19:14:43.359107124Z [1705173283] unbound[246:2] info: processQueryTargets: x2.c.lencr.org. AAAA IN

2024-01-13T19:14:43.359121197Z [1705173283] unbound[246:2] debug: return error response SERVFAIL

2024-01-13T19:14:43.359135179Z [1705173283] unbound[246:2] debug: validator[module 1] operate: extstate:module_wait_module event:module_event_moddone

2024-01-13T19:14:43.359149678Z [1705173283] unbound[246:2] info: validator operate: query x2.c.lencr.org. AAAA IN

2024-01-13T19:14:43.359164141Z [1705173283] unbound[246:2] debug: subnetcache[module 0] operate: extstate:module_wait_module event:module_event_moddone

2024-01-13T19:14:43.359178455Z [1705173283] unbound[246:2] info: subnetcache operate: query x2.c.lencr.org. AAAA IN

2024-01-13T19:14:43.359193918Z [1705173283] unbound[246:2] debug: iterator[module 2] operate: extstate:module_wait_subquery event:module_event_pass

2024-01-13T19:14:43.359208436Z [1705173283] unbound[246:2] info: iterator operate: query x2.c.lencr.org. A IN

2024-01-13T19:14:43.359222621Z [1705173283] unbound[246:2] info: processQueryTargets: x2.c.lencr.org. A IN

2024-01-13T19:14:43.359236658Z [1705173283] unbound[246:2] debug: return error response SERVFAIL
```

What could be causing it? I'm using the default docker run.
Device is RPI4b 8GB running RPI OS Lite x64

**Comment by origamiofficial** [comment] 2024-01-14 14:24
Can you set the `log-servfail` value from `no` to `yes` in the config and try again? I haven't noticed anything on my end!

**Comment by chriexpe** [comment] 2024-01-14 17:42
Looking closely at timestamp there are a ton of queries each second, so I couldn't find anything, but on Pihole these are the errors:
![image](https://github.com/origamiofficial/docker-pihole-unbound/assets/16724821/b80a489f-a740-41e3-86da-7fd374f2c621)
And this (bing domain gives a ton of these errors where the page will only load after another refresh or two)
![image](https://github.com/origamiofficial/docker-pihole-unbound/assets/16724821/05ad6b17-ffbe-4698-907f-b7fcc2edba21)
And this is the log of that exact second as the servfail happened.
[pihole-unbound_logs(1).txt](https://github.com/origamiofficial/docker-pihole-unbound/files/13932510/pihole-unbound_logs.1.txt)

**Comment by origamiofficial** [comment] 2024-01-14 18:29
Completely remove your current container and images then check the new image I've just pushed as `beta` tag `rlabinc/pihole-unbound:beta`. Try that image and let me know!

**Comment by origamiofficial** [comment] 2024-01-14 18:59
You can also check your date and time are correct, the correct timezone etc.
```bash
timedatectl
```
Then check your Docker container `-e TZ=Europe/London` value to set as per your region. Unbound DNSSEC needed correct date and time!

**Comment by origamiofficial** [comment] 2024-01-14 19:12
I'm using the new Beta image & can't reproduce it from my end, tried with your SERVFAIL domains! Once confirmed, I'll push the necessary changes to the stable image.

<img width="717" alt="image" src="https://github.com/origamiofficial/docker-pihole-unbound/assets/64251776/09223638-65f4-414f-958e-703027964fb4">

**Comment by origamiofficial** [comment] 2024-01-15 15:54
I'm closing this issue as completed, tested new images several times and found no error. Update your image from any tag you wish ASAP. If you still facing the issue, reopen this and let me know!

**Closed as completed by origamiofficial** 2024-01-15 15:54 UTC

**Comment by chriexpe** [comment] 2024-02-08 01:20
> I'm closing this issue as completed, tested new images several times and found no error. Update your image from any tag you wish ASAP. If you still facing the issue, reopen this and let me know!

Felt bad that I didn't thank you before but thanks, it fixed those SERVFAIL, but ocassionally there where still some issues with Unbound such as some pages not loading at all or propperly (I.E. only text), and quite a few issues with Windows Update not working, I don't have much info as I couldn't find where I saved screenshots but here is one of it when accessing https://dnscheck.tools/:
```[1707354584] unbound[246:0] error: SERVFAIL <www.dnscheck.tools. A IN>: exceeded the maximum nameserver nxdomains
[1707354584] unbound[246:0] info: resolving www.dnscheck.tools. A IN
[1707354584] unbound[246:0] info: resolving hope.ns.cloudflare.com. AAAA IN
[1707354584] unbound[246:0] info: resolving chuck.ns.cloudflare.com. AAAA IN
[1707354584] unbound[246:0] info: resolving chuck.ns.cloudflare.com. A IN
[1707354584] unbound[246:0] info: resolving dnscheck.tools. DNSKEY IN
[1707354584] unbound[246:0] info: resolving hope.ns.cloudflare.com. A IN
[1707354584] unbound[246:0] info: resolving hope.ns.cloudflare.com. AAAA IN
[1707354584] unbound[246:0] info: resolving hope.ns.cloudflare.com. A IN
[1707354584] unbound[246:1] info: response for hope.ns.cloudflare.com. AAAA IN
[1707354584] unbound[246:1] info: reply from <com.> 192.26.92.30#53
[1707354584] unbound[246:1] info: query response was REFERRAL
[1707354584] unbound[246:1] error: SERVFAIL <www.dnscheck.tools. AAAA IN>: exceeded the maximum nameserver nxdomains
[1707354584] unbound[246:0] info: response for hope.ns.cloudflare.com. A IN
[1707354584] unbound[246:0] info: reply from <com.> 192.26.92.30#53
[1707354584] unbound[246:0] info: query response was REFERRAL
[1707354584] unbound[246:0] info: response for hope.ns.cloudflare.com. AAAA IN
[1707354584] unbound[246:0] info: reply from <com.> 192.12.94.30#53
[1707354584] unbound[246:0] info: query response was REFERRAL
[1707354584] unbound[246:0] error: SERVFAIL <www.dnscheck.tools. A IN>: exceeded the maximum nameserver nxdomains
```

**Comment by origamiofficial** [comment] 2024-02-08 02:28
I've recently pushed a new update with stable unbound release, have you updated to check if it fixed or not?
Also I find out this issue in unbound repo: https://github.com/NLnetLabs/unbound/issues/362

**Comment by chriexpe** [comment] 2024-02-17 02:49
> I've recently pushed a new update with stable unbound release, have you updated to check if it fixed or not? Also I find out this issue in unbound repo: [NLnetLabs/unbound#362](https://github.com/NLnetLabs/unbound/issues/362)

Hmm I thought so, it's outside of Unbound's control, but latelly it seems stable, tho on this issue they said that by just restarting unbound it might fix, maybe I'll set a cron to restart the service each few days if it gets worse.
Also, is it possible to "permit all origins" by default? Because "only local requests" would work only if my network was "inside" the docker right? Seems that this option was designed mostly for "bare metal" pihole.
![image](https://github.com/origamiofficial/docker-pihole-unbound/assets/16724821/ab274498-9409-4599-bf09-a820288cdfbb)

**Comment by origamiofficial** [comment] 2024-02-17 05:00
Pi-hole team push their official docker image with this settings. User's need to change it if needed. In my image, I do not touch the pi-hole installation inside the docker image to avoid any potential bugs.
